# import pandas as pd

# df = pd.read_csv('SraRunTable.txt', sep=',', header=0)

# # append all accession number to a list
# ACCESSIONS = []

# for i in df['Run']:
#     ACCESSIONS.append(i)

# rule all:
#     input:
#         expand("fastq/se/{accession}.fastq.gz", accession=ACCESSIONS)

# rule get_fastq_se:
#     output: "fastq/se/{accession}.fastq.gz"
#     log: "logs/se/{accession}.log"
#     params:
#         extra="--skip-technical"
#     threads: 16
#     wrapper:
#         "0.80.2/bio/sra-tools/fasterq-dump"