configfile: "config.yaml"

rule all:
    input: 
        "reports/multiqc_report_lemons.html"

rule fetch_fastq:
    output:
        directory("fastq_lemons")
    params:
        names=config["name"]
    shell:
        "parallel-fastq-dump --sra-id {params.names} --threads 16 --outdir {output} --gzip"

rule fastq_qc:
    input:
        "fastq_lemons/{name}.fastq.gz"
    output:
        html="fastq_lemons/qc/{name}_fastqc.html",
        zip="fastq_lemons/qc/{name}_fastqc.zip"
        # OR
        #directory("fastq_lemons/qc")
    shell:
        "fastqc -t 16 {input} -o {output}"

rule trim_filter:
    input:
        "fastq_lemons/{name}.fastq.gz"
    output:
        "trimmed_lemons/{name}.fastq.gz"
    shell:
        "cutadapt -j 16 -m 20 --cut 10 -o {output} {input}"

rule trim_qc:
    input:
        "trimmed_lemons/{name}.fastq.gz"
    output:
        html="trimmed_lemons/qc/{name}_fastqc.html",
        zip="trimmed_lemons/qc/{name}_fastqc.zip"
    shell:
        "fastqc -t 16 {input} -o {output}"

rule report:
    output:
        "reports/multiqc_report_lemons.html"
    params:
        fastq_lemons="fastq_lemons/qc/",
        trimmed_lemons="trimmed_lemons/qc/"
    shell:
        "multiqc --force -d {params.fastq_lemons} {params.trimmed_lemons} -n {output}"
